### PR TITLE
Sensitivity Clutch 

### PR DESCRIPTION
**Pull request by Noffyrg**

### CODE REVIEW

**Review by Comptsy — APPROVED** [review]
For probably the first time this year, I saw the mechanism in question work before it was pushed

**Review by JohnRosner — APPROVED** [review]
Looks good

**Comment by Noffyrg** [comment]
Sun is down, feeling cold
That's how we already know winter's here
My driver would prolly do it for a blue banner
That's just all he know, he don't know nothin' else
I tried to show 'em, yeah
I tried to show 'em, yeah, yeah
Yeah, yeah, yeah
Gone on you with the pitch and roll
Young Miko, he in Joysticko mode

**Review by programmer94 — APPROVED** [review]
Looks good.

**Review by jcsidawy — APPROVED** [review]
Good

**Pull request merged**
